// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spg.TestAdministrator.Services.Models;

namespace Spg.TestAdministrator.Services.Migrations
{
    [DbContext(typeof(TestsContext))]
    [Migration("20200924190958_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Lesson", b =>
                {
                    b.Property<long>("L_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("L_Class")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<long?>("L_Day")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("L_Hour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("0");

                    b.Property<string>("L_Room")
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("L_Subject")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("L_Teacher")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<long?>("L_Untis_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("0");

                    b.HasKey("L_ID");

                    b.HasIndex("L_Class")
                        .HasName("SchoolclassLesson");

                    b.HasIndex("L_Hour")
                        .HasName("PeriodLesson");

                    b.HasIndex("L_Teacher")
                        .HasName("TeacherLesson");

                    b.HasIndex("L_Untis_ID")
                        .HasName("idx_L_Untis_ID");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Period", b =>
                {
                    b.Property<long>("P_Nr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("P_From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P_To")
                        .HasColumnType("datetime2");

                    b.HasKey("P_Nr");

                    b.ToTable("Period");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Pupil", b =>
                {
                    b.Property<long>("P_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("P_Account")
                        .IsRequired()
                        .HasColumnType("VARCHAR(16)");

                    b.Property<string>("P_Class")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("P_Firstname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("P_Lastname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("P_ID");

                    b.HasIndex("P_Account")
                        .IsUnique()
                        .HasName("idx_P_Account");

                    b.HasIndex("P_Class")
                        .HasName("SchoolclassPupil");

                    b.ToTable("Pupil");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Schoolclass", b =>
                {
                    b.Property<string>("C_ID")
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("C_ClassTeacher")
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("C_Department")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.HasKey("C_ID");

                    b.HasIndex("C_ClassTeacher")
                        .HasName("TeacherSchoolclass");

                    b.ToTable("Schoolclass");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Teacher", b =>
                {
                    b.Property<string>("T_ID")
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("T_Account")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("T_Email")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("T_Firstname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("T_Lastname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("T_ID");

                    b.HasIndex("T_Account")
                        .IsUnique()
                        .HasName("idx_T_Account");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Test", b =>
                {
                    b.Property<long>("TE_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("TE_Class")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<byte[]>("TE_Date")
                        .IsRequired()
                        .HasColumnType("TIMESTAMP");

                    b.Property<long>("TE_Lesson")
                        .HasColumnType("bigint");

                    b.Property<string>("TE_Subject")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("TE_Teacher")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.HasKey("TE_ID");

                    b.HasIndex("TE_Class")
                        .HasName("SchoolclassTest");

                    b.HasIndex("TE_Lesson")
                        .HasName("PeriodTest");

                    b.HasIndex("TE_Teacher")
                        .HasName("TeacherTest");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Lesson", b =>
                {
                    b.HasOne("Spg.TestAdministrator.Services.Models.Schoolclass", "L_ClassNavigation")
                        .WithMany("Lesson")
                        .HasForeignKey("L_Class")
                        .IsRequired();

                    b.HasOne("Spg.TestAdministrator.Services.Models.Period", "L_HourNavigation")
                        .WithMany("Lesson")
                        .HasForeignKey("L_Hour");

                    b.HasOne("Spg.TestAdministrator.Services.Models.Teacher", "L_TeacherNavigation")
                        .WithMany("Lesson")
                        .HasForeignKey("L_Teacher")
                        .IsRequired();
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Pupil", b =>
                {
                    b.HasOne("Spg.TestAdministrator.Services.Models.Schoolclass", "P_ClassNavigation")
                        .WithMany("Pupil")
                        .HasForeignKey("P_Class")
                        .IsRequired();
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Schoolclass", b =>
                {
                    b.HasOne("Spg.TestAdministrator.Services.Models.Teacher", "C_ClassTeacherNavigation")
                        .WithMany("Schoolclass")
                        .HasForeignKey("C_ClassTeacher");
                });

            modelBuilder.Entity("Spg.TestAdministrator.Services.Models.Test", b =>
                {
                    b.HasOne("Spg.TestAdministrator.Services.Models.Schoolclass", "TE_ClassNavigation")
                        .WithMany("Test")
                        .HasForeignKey("TE_Class")
                        .IsRequired();

                    b.HasOne("Spg.TestAdministrator.Services.Models.Period", "TE_LessonNavigation")
                        .WithMany("Test")
                        .HasForeignKey("TE_Lesson")
                        .IsRequired();

                    b.HasOne("Spg.TestAdministrator.Services.Models.Teacher", "TE_TeacherNavigation")
                        .WithMany("Test")
                        .HasForeignKey("TE_Teacher")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
